# Generated by Django 2.2.6 on 2021-10-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='教学楼名称')),
                ('show_schedule', models.BooleanField(default=True, verbose_name='课表显示')),
                ('show_classroom', models.BooleanField(default=True, verbose_name='自习室显示')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('name', models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, verbose_name='校区')),
                ('show_schedule', models.BooleanField(default=True, verbose_name='课表显示')),
                ('show_classroom', models.BooleanField(default=True, verbose_name='自习室显示')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.CharField(blank=True, max_length=128, primary_key=True, serialize=False, verbose_name='教室ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='教室名称')),
                ('show_schedule', models.BooleanField(default=True, verbose_name='课表显示')),
                ('show_classroom', models.BooleanField(default=True, verbose_name='自习室显示')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Building')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomType',
            fields=[
                ('name', models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, verbose_name='教室类型')),
                ('show_schedule', models.BooleanField(default=True, verbose_name='课表显示')),
                ('show_classroom', models.BooleanField(default=True, verbose_name='自习室显示')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, verbose_name='教师ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='教师姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('name', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, verbose_name='学期')),
                ('firstMonday', models.DateField(verbose_name='第一周的周一日期')),
                ('start', models.DateField(verbose_name='开学日期')),
                ('end', models.DateField(verbose_name='结束日期')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(blank=True, max_length=128, null=True, verbose_name='课程ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='课程名称')),
                ('CLASS_TIME', models.CharField(blank=True, max_length=32, null=True, verbose_name='上课时间')),
                ('START_TIME', models.CharField(blank=True, max_length=32, null=True, verbose_name='课程安排')),
                ('showtext', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注上课安排')),
                ('XQ', models.CharField(blank=True, max_length=32, null=True, verbose_name='星期')),
                ('KS', models.IntegerField(default=0, verbose_name='开始的课节')),
                ('JS', models.IntegerField(default=0, verbose_name='结束的课节')),
                ('ZC1', models.IntegerField(default=0, verbose_name='第几周开始课程')),
                ('ZC2', models.IntegerField(default=0, verbose_name='第几周结束课程')),
                ('SJBZ', models.IntegerField(default=0, verbose_name='有无课程')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Term')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassroomType'),
        ),
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Campus'),
        ),
    ]
